name: Deploy to Vercel

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          VERCEL_DEPLOY_URL=$(vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm)
          echo "Deployment URL: $VERCEL_DEPLOY_URL"

      - name: Check Vercel Deployment Status
        run: |
          DEPLOYMENT_ID=$(echo "$VERCEL_DEPLOY_URL" | grep -o 'deployment_id=[^&]*' | cut -d '=' -f 2)
          STATUS=$(vercel inspect $DEPLOYMENT_ID --token ${{ secrets.VERCEL_TOKEN }} --json | jq -r '.status')

          if [ "$STATUS" != "READY" ]; then
            echo "Deployment failed with status: $STATUS"
            exit 1
          else
            echo "Deployment successful with status: $STATUS"
          fi
