name: Deploy to Vercel

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: |
          VERCEL_DEPLOY_URL=$(vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes)
          echo "Deployment URL: $VERCEL_DEPLOY_URL"

      - name: Check Vercel Deployment Status
        run: |
          # Extract the deployment URL (it looks like my-deployment.vercel.app)
          DEPLOYMENT_URL=$(echo "$VERCEL_DEPLOY_URL" | sed 's/.*\(https:\/\/[^ ]*\).*/\1/')
          echo "Deployment URL: $DEPLOYMENT_URL"

          # Inspect the deployment using the URL directly
          STATUS=$(vercel inspect $DEPLOYMENT_URL --token ${{ secrets.VERCEL_TOKEN }} | grep 'State' | awk '{print $2}')

          if [ "$STATUS" != "READY" ]; then
            echo "Deployment failed with status: $STATUS"
            exit 1
          else
            echo "Deployment successful with status: $STATUS"
          fi
