name: Deploy to Vercel

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: VERCEL_DEPLOY_URL=$(vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes)

      - name: Check Vercel Deployment Status
        run: |
          echo "Deployment URL: $VERCEL_DEPLOY_URL"
          STATUS=$(vercel inspect $DEPLOYMENT_URL --token ${{ secrets.VERCEL_TOKEN }} | grep 'State' | awk '{print $2}')

          if [ "$STATUS" != "READY" ]; then
            echo "Deployment failed with status: $STATUS"
            exit 1
          else
            echo "Deployment successful with status: $STATUS"
          fi
